create table if not exists public.plano_arq_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plano_arq_state (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  device_id text,
  updated_at timestamptz not null default now(),
  unique (user_id, key)
);

create index if not exists plano_arq_state_user_updated_idx
  on public.plano_arq_state (user_id, updated_at desc);

alter table public.plano_arq_profiles enable row level security;
alter table public.plano_arq_state enable row level security;

drop policy if exists "plano_arq_profiles_select_own" on public.plano_arq_profiles;
create policy "plano_arq_profiles_select_own"
  on public.plano_arq_profiles for select
  using (auth.uid() = user_id);

drop policy if exists "plano_arq_profiles_insert_own" on public.plano_arq_profiles;
create policy "plano_arq_profiles_insert_own"
  on public.plano_arq_profiles for insert
  with check (auth.uid() = user_id);

drop policy if exists "plano_arq_profiles_update_own" on public.plano_arq_profiles;
create policy "plano_arq_profiles_update_own"
  on public.plano_arq_profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "plano_arq_state_select_own" on public.plano_arq_state;
create policy "plano_arq_state_select_own"
  on public.plano_arq_state for select
  using (auth.uid() = user_id);

drop policy if exists "plano_arq_state_insert_own" on public.plano_arq_state;
create policy "plano_arq_state_insert_own"
  on public.plano_arq_state for insert
  with check (auth.uid() = user_id);

drop policy if exists "plano_arq_state_update_own" on public.plano_arq_state;
create policy "plano_arq_state_update_own"
  on public.plano_arq_state for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "plano_arq_state_delete_own" on public.plano_arq_state;
create policy "plano_arq_state_delete_own"
  on public.plano_arq_state for delete
  using (auth.uid() = user_id);

create or replace function public.plano_arq_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists plano_arq_profiles_touch_updated_at on public.plano_arq_profiles;
create trigger plano_arq_profiles_touch_updated_at
before update on public.plano_arq_profiles
for each row execute function public.plano_arq_touch_updated_at();

drop trigger if exists plano_arq_state_touch_updated_at on public.plano_arq_state;
create trigger plano_arq_state_touch_updated_at
before update on public.plano_arq_state
for each row execute function public.plano_arq_touch_updated_at();
