const VERSION='19.1-source';
const CORE=`plano-arq-core-${VERSION}`,RUNTIME=`plano-arq-runtime-${VERSION}`,OFFLINE=`plano-arq-offline-${VERSION}`;
const CORE_URLS=['./','./index.html','./offline.html','./manifest.webmanifest','./assets/css/pa-tokens-v01.css','./assets/css/pa-components-v01.css','./assets/css/pa-shell-v16.css','./assets/js/pa-pwa-v01.js','./assets/js/pa-shell-v16.js','./assets/js/pa-data-v03.js','./assets/js/pa-sync-v03.js','./assets/js/pa-drive-v01.js','./assets/js/pa-actions-v01.js','./data/navigation.js','./data/contests.js','./data/materials.js','./data/exam-schemas.js','./data/question-catalog.js','./data/review-catalog.js','./data/simulations.js','./data/cloud-config.js','./data/offline-pack.json'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CORE).then(async c=>{for(const url of CORE_URLS){try{const r=await fetch(url,{cache:'reload'});if(r.ok)await c.put(url,r)}catch(_){}}}))});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keep=new Set([CORE,RUNTIME,OFFLINE]);for(const k of await caches.keys())if(k.startsWith('plano-arq-')&&!keep.has(k))await caches.delete(k);await self.clients.claim()})())});
async function networkFirst(req){const c=await caches.open(RUNTIME);try{const r=await fetch(req);if(r&&r.ok)c.put(req,r.clone());return r}catch(_){return(await c.match(req))||(await caches.match(req))||(req.mode==='navigate'?await caches.match('./offline.html'):Response.error())}}
async function cacheFirst(req){const hit=await caches.match(req);if(hit)return hit;try{const r=await fetch(req);if(r&&(r.ok||r.type==='opaque')){const c=await caches.open(RUNTIME);c.put(req,r.clone())}return r}catch(_){return Response.error()}}
async function staleWhileRevalidate(req){const c=await caches.open(RUNTIME),hit=await c.match(req);const fresh=fetch(req).then(r=>{if(r&&(r.ok||r.type==='opaque'))c.put(req,r.clone());return r}).catch(()=>null);return hit||(await fresh)||Response.error()}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const u=new URL(req.url);if(req.mode==='navigate'){event.respondWith(networkFirst(req));return}if(u.origin!==location.origin){if(req.destination==='image'){event.respondWith(cacheFirst(req));}return}if(/\/(materials|simulados)\//.test(u.pathname)){event.respondWith(networkFirst(req));return}if(/\/edital\//.test(u.pathname)){event.respondWith(cacheFirst(req));return}if(['style','script','font'].includes(req.destination)||/\/data\//.test(u.pathname)){event.respondWith(networkFirst(req));return}if(req.destination==='image'){event.respondWith(cacheFirst(req));return}event.respondWith(networkFirst(req))});
async function cacheUrls(urls){const c=await caches.open(OFFLINE);let cached=0,failed=0;for(const rel of urls||[]){try{const url=new URL(rel,self.registration.scope).href,r=await fetch(url,{cache:'reload'});if(r.ok){await c.put(url,r.clone());cached++}else failed++}catch(_){failed++}}return{ok:true,cached,failed}}
async function cacheCounts(){const off=await caches.open(OFFLINE),run=await caches.open(RUNTIME),core=await caches.open(CORE);return{ok:true,offlineCount:(await off.keys()).length,runtimeCount:(await run.keys()).length,coreCount:(await core.keys()).length,version:VERSION}}
self.addEventListener('message',event=>{const msg=event.data||{},port=event.ports?.[0];const reply=x=>port?.postMessage(x);if(msg.type==='SKIP_WAITING'){self.skipWaiting();reply({ok:true});return}if(msg.type==='CACHE_URLS'){event.waitUntil(cacheUrls(msg.payload?.urls).then(reply).catch(e=>reply({ok:false,error:e.message})));return}if(msg.type==='CLEAR_OFFLINE'){event.waitUntil(caches.delete(OFFLINE).then(()=>reply({ok:true})).catch(e=>reply({ok:false,error:e.message})));return}if(msg.type==='CACHE_INFO'){event.waitUntil(cacheCounts().then(reply).catch(e=>reply({ok:false,error:e.message})));return}});